app/Modules/Fruitstory/routes/web.php
<?php

Route::group([
    'prefix' => 'lora',
    'as' => 'lora.',
    'middleware' => [ 'web', 'language'],
    'namespace' => 'App\Modules\Fruitstory\Http\Controllers'], function () {

    Route::group(['middleware' => 'guardAuth:admin'], function() {
        Route::resource('orders.items', 'OrderItemsController');
        Route::resource('orders', 'OrdersController');
        Route::resource('categories','CategoryController');
        Route::post('products/{product}','ProductController@update')->name('products.update');
        Route::resource('products','ProductController')->except('update');
        Route::resource('users','UserResourceController');
        Route::resource('units', 'UnitsController');
        Route::delete('news/{news_id}/images/{image_id}','NewsController@removeImage');
        Route::resource('news', 'NewsController');
        Route::resource('promo', 'PromoCodeController');
        Route::resource('delivery-areas', 'DeliveryAreasController');
        Route::resource('cities', 'CitiesController');
        Route::get('bonuses', 'BonusesController@index');
        Route::put('bonuses', 'BonusesController@update')->name('bonuses.update');

    });
});

app/Modules/Fruitstory/Http/Controllers/NewsController.php
<?php

namespace App\Modules\Fruitstory\Http\Controllers;

use Dosarkz\Lora\Installation\Modules\Lora\Http\Controllers\BasicController;
use Dosarkz\Lora\Installation\Modules\Lora\Models\Image;
use App\Models\News;
use App\Repositories\File\NewsImageUploader;
use App\Http\Controllers\Controller;
use App\Http\Requests;
use Carbon\Carbon;
use Dosarkz\LaravelUploader\ImageUploader;
use Illuminate\Support\Facades\Redirect;
use Illuminate\Support\Facades\Session;

class NewsController extends BasicController
{
    public function __construct()
    {
        $this->setModel(new News());
        $this->setViewPath('fruitstory');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $news = $this->getModel()->orderBy('created_at','DESC')->paginate();
        return $this->view('news.index', ['news' => $news]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $model = $this->getModel();
        $model->created_at = Carbon::now();
        return $this->view('news.create', ['model' => $model]);
    }

    /**
     * @param Requests\StoreNewsRequest $request
     * @return \Illuminate\Foundation\Application|\Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function store(Requests\StoreNewsRequest $request)
    {
        $request->merge([
            'user_id' => auth('admin')->user()->id,
            'alias' => $this->trans_url($request->input('title')),
            'created_at'  => date('Y-m-d h:i:s',strtotime($request->input('created_at'))),
        ]);

        $news = $this->getModel()->create($request->all());

        if ($request->input('on_main') == 'on')
        {
            $news->update([
                'on_main' => true
            ]);
        }

        $this->uploadImage($news, $request);
        return redirect(route('lora.news.index'))->with('success','Успешно');
    }

    private function uploadImage($model, $request) : bool
    {
        if ($request->hasFile('image'))
        {
            $uploader = new ImageUploader($request->file('image'), 'images/news/');

            $model->image()->create([
                'name' => $uploader->getFileName(),
                'thumb' => $uploader->getThumb(),
                'path' => $uploader->destination
            ]);

            return true;
        }
        return false;
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $model = $this->getModel()->findOrFail($id);
        return $this->view('news.edit', ['model' => $model]);
    }

    public function show($id)
    {
        $model = $this->getModel()->findOrFail($id);
        return view('news.show',compact('model'));
    }

    /**
     * @param Requests\StoreNewsRequest $request
     * @param $id
     * @return \Illuminate\Foundation\Application|\Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function update(Requests\StoreNewsRequest $request, $id)
    {
        $model = $this->getModel()->findOrFail($id);

        $request->merge([
            'created_at' => date('Y-m-d h:i:s',strtotime($request->input('created_at')))
        ]);

        if (!$request->has('on_main'))
        {
            $request->merge([
                'on_main' => 0
            ]);
        }else{
            if ($request->input('on_main') == 'on')
            {
                $request->merge([
                    'on_main' => 1
                ]);
            }
        }

        $model->update($request->all());
        $this->uploadImage($model, $request);
        return redirect(route('lora.news.index'))->with('success','Успешно');
    }

    /**
     * @param $id
     * @return \Illuminate\Foundation\Application|\Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function destroy($id)
    {
        $news = $this->getModel()->findOrFail($id);
        $news->delete();
        return redirect(route('lora.news.index'))->with('success', 'Новость успешно удалена!');
    }

    public function removeImage($news_id, $image_id)
    {
        $image = Image::findOrFail($image_id);

        if(file_exists(public_path($image->getThumb())))
        {
            unlink(public_path($image->getThumb()));
        }
        if(file_exists(public_path($image->getFullImage())))
        {
            unlink(public_path($image->getFullImage()));
        }

        $image->delete();
        return redirect()->back()->with('success', 'Фото удалено');
    }

}

app/Modules/Fruitstory/Resources/views/news/create.blade.php
@extends('lora::layouts.app')

@section('css')
    <link rel="stylesheet" href="/plugins/datepicker/datepicker3.css">
@endsection

@section('js')
    <script src="/templateEditor/ckeditor/ckeditor.js"></script>
@endsection
@section('js-append')
    <script src="/plugins/datepicker/bootstrap-datepicker.js"></script>
    <script src="/plugins/datepicker/locales/bootstrap-datepicker.ru.js"></script>
    <script>
        $(document).ready(function() {
            $('#datepicker').datepicker({
                isRTL: false,
                format: 'yyyy-mm-dd',
                language: 'ru'
            });
        });

        CKEDITOR.replace('description');
        CKEDITOR.replace('short_description');
    </script>
@endsection
@section('content')
    <div class="card">
        <div class="card-header">
            <h3 class="panel-heading">Добавить новость</h3>
        </div>
        <div class="card-body">
            @include('fruitstory::news.form')
        </div>
    </div>
@endsection

app/Modules/Fruitstory/Resources/views/news/edit.blade.php
@extends('lora::layouts.app')

@section('content')
    <div class="card">
        <div class="card-header">
            <h3 class="panel-heading">Редактировать новость # {{$model->id}}</h3>
        </div>
        <div class="card-body">
            @include('fruitstory::news.form')
        </div>
    </div>
@endsection


@section('css')
    <link rel="stylesheet" href="/plugins/datepicker/datepicker3.css">
@endsection

@section('js')
    <script src="/templateEditor/ckeditor/ckeditor.js"></script>
@endsection
@section('js-append')
    <script src="/plugins/datepicker/bootstrap-datepicker.js"></script>
    <script src="/plugins/datepicker/locales/bootstrap-datepicker.ru.js"></script>
    <script>
        $(document).ready(function() {
            $('#datepicker').datepicker({
                isRTL: false,
                format: 'yyyy-mm-dd',
                language: 'ru'
            });
        });

        $(document).ready(function(){
            $('#remove-image').on('show.bs.modal', function (event) {
                var button = $(event.relatedTarget);
                var news_id = button.data('news_id');
                var image_id = button.data('image_id');
                var modal = $(this);
                modal.find('#removeImageForm').attr('action','/lora/news/'+ news_id +'/images/'+image_id)
            })
        });

        CKEDITOR.replace('description');
        CKEDITOR.replace('short_description');
    </script>
@endsection

app/Modules/Fruitstory/Resources/views/news/form.blade.php
        @if (count($errors) > 0)
            <div class="alert alert-danger">
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
        @endif

        @if($model->exists)
            {{ Form::open(array('url' => route('lora.news.update', $model->id),'method'=> 'PUT', 'name'=>'updateNews', 'files' => true))}}
        @else
            {{ Form::open(array('url' => route('lora.news.store'),'method'=> 'POST', 'files' => true, 'name'=>'addNews'))}}
        @endif

        <div class="box-body">
            <div class="form-group">
                <label class="control-label" for="title">Заголовок</label>
                {{Form::text('title',$model->title, ['class' => 'form-control']) }}
            </div>

            <div class="form-group">
                <label class="control-label" for="preview">Фото</label>
                <input type="file" id="image_id" name="image">
            </div>

            @if($model->exists and $model->image)
                <img width="150" src="{{url($model->image->getThumb())}}" alt="">
                <button type="button" class="btn btn-warning remove-image"
                        data-news_id="{{$model->id}}" data-image_id="{{$model->image->id}}"
                        data-toggle="modal" data-target="#remove-image">
                    <span  class="glyphicon glyphicon-remove"></span> удалить
                </button>
            @endif

            <div class="form-group">
                <label class="control-label" for="title">Дата</label>

                {{Form::date('created_at', date('Y-m-d',strtotime($model->created_at)),
     ['class' => 'form-control']) }}
            </div>

            <div class="form-group">
                <label class="control-label" for="short_description">Краткое описание</label>
                {{Form::textarea('short_description',$model->short_description, ['class' => 'form-control',
                'id' => 'short_description', 'cols' => 10, 'rows' => 10
                ]) }}
            </div>

            <div class="form-group">
                <label class="control-label" for="description">Подробное описание</label>
                {{Form::textarea('description',$model->description, ['class' => 'form-control',
                'id' => 'description', 'cols' => 10, 'rows' => 10
                ]) }}
            </div>

            {{--<div class="form-group">--}}
                {{--<label class="control-label" for="title">На главной</label>--}}
                {{--<br>--}}
                {{--@if($model->exists)--}}
                    {{--{{Form::checkbox('on_main', null, $model->on_main, ['data-toggle' => 'toggle', 'data-on' => 'Да',--}}
                    {{--'data-off' => 'Нет']) }}--}}
                {{--@else--}}
                    {{--{{Form::checkbox('on_main',null,null,['data-toggle' => 'toggle', 'data-on' => 'Да',--}}
                    {{--'data-off' => 'Нет']) }}--}}
                {{--@endif--}}
            {{--</div>--}}

            <div class="form-group">
                <label class="control-label" for="title">Статус</label>
                {{Form::select('status_id', [1=> 'Активен', 0 => 'Не активен'],$model->status_id,['class'   => 'form-control', 'placeholder' => 'Не выбрано'])}}
            </div>

            <div class="form-group">
                @if($model->exists)
                    {{ form::submit('Обновить', ['class' => 'btn btn-primary']) }}
                @else
                    {{ form::submit('Создать', ['class' => 'btn btn-primary']) }}
                @endif

            </div>


        </div>
        {{ Form::close() }}


@include('modals.remove_image_modal')

app/Modules/Fruitstory/Resources/views/news/index.blade.php
@extends('lora::layouts.app')

@section('content')

    <div class="card card-default">
        <div class="card-header">
            <h3>Новости</h3>
        </div>

        <div class="card-body">
            <table class="table table-hover" data-form="deleteForm">
                <thead class="thead-inverse">
                <tr>
                    <th>id</th>
                    <th>Название</th>
                    <th>Статус</th>
                    <th>Действия</th>
                </tr>
                </thead>
                <tbody>
                @foreach($news as $item)

                    <tr>
                        <td>{{$item->id}}</td>
                        <td>{{ $item->title }}</td>
                        <td>{{$item->status_id == \App\Models\News::STATUS_ACTIVE ? 'Активен' : 'Не активен'}}</td>
                        <td>
                            <a class="btn btn-sm btn-primary" href="{{route('lora.news.edit', $item->id)}}">
                                <i class="fas fa-edit" aria-hidden="true"></i></a>

                            <button class="btn btn-sm btn-danger delete" type="button"
                                    data-target="#confirm"
                                    data-toggle="modal" data-action="{{route('lora.news.destroy', $item->id)}}">
                                <i class="fas fa-times" aria-hidden="true"></i></button>
                        </td>
                    </tr>

                @endforeach
                </tbody>
            </table>
        </div>
        <div class="card-footer">
            <div class="col-md-10">
                <div class="form-group">
                    {{ $news->links() }}
                </div>
            </div>
            @include('lora::modals.base_modal')
        </div>

    </div>

@endsection

@section('js-append')

    <script>
        $('#confirm').on('show.bs.modal', function (event) {
            var button = $(event.relatedTarget);
            var modal = $(this);

            modal.find('#removeForm').attr('action', button.data('action'))
        })
    </script>
@endsection