app/Modules/Fruitstory/routes/web.php
<?php

Route::group([
    'prefix' => 'lora',
    'as' => 'lora.',
    'middleware' => [ 'web', 'language'],
    'namespace' => 'App\Modules\Fruitstory\Http\Controllers'], function () {

    Route::group(['middleware' => 'guardAuth:admin'], function() {
        Route::resource('orders.items', 'OrderItemsController');
        Route::resource('orders', 'OrdersController');
        Route::resource('categories','CategoryController');
        Route::post('products/{product}','ProductController@update')->name('products.update');
        Route::resource('products','ProductController')->except('update');
        Route::resource('users','UserResourceController');
        Route::resource('units', 'UnitsController');
        Route::delete('news/{news_id}/images/{image_id}','NewsController@removeImage');
        Route::resource('news', 'NewsController');
        Route::resource('promo', 'PromoCodeController');
        Route::resource('delivery-areas', 'DeliveryAreasController');
        Route::resource('cities', 'CitiesController');
        Route::get('bonuses', 'BonusesController@index');
        Route::put('bonuses', 'BonusesController@update')->name('bonuses.update');

    });
});

app/Modules/Fruitstory/Http/Controllers/OrdersController.php
<?php
/**
 * Created by PhpStorm.
 * User: dosarkz
 * Date: 2019-03-23
 * Time: 17:33
 */

namespace App\Modules\Fruitstory\Http\Controllers;

use App\Http\Requests\UpdateOrderRequest;
use App\Models\Order;
use Dosarkz\Lora\Installation\Modules\Lora\Http\Controllers\BasicController;

class OrdersController extends BasicController
{
    public function __construct()
    {
        $this->setModel(new Order());
        $this->setViewPath('fruitstory');
    }

    public function index()
    {
        $models = $this->getModel()::orderBy('created_at', 'desc')->paginate('10');
        return $this->view('orders.index', compact('models'));
    }

    /**
     * Remove the order
     *
     * */
    public function destroy($id)
    {
        $model = Order::findOrFail($id);
        $model->orderItems()->delete();
        $model->delete();

        return redirect()->back()->with('success', 'Success');
    }

    public function edit($id)
    {
        $model = Order::findOrFail($id);
        return $this->view('orders.edit', compact('model'));
    }

    public function update(UpdateOrderRequest $request, $id)
    {
        $model = Order::findOrFail($id);
        $model->update($request->all());

        return redirect(route('lora.orders.index'))->with('success', 'Success');
    }
}

app/Modules/Fruitstory/Resources/views/orders/edit.blade.php
@extends('lora::layouts.app')

@section('content')
    <div class="card">
        <div class="card-header">
            <h3 class="panel-heading">Редактировать заказ # {{$model->id}}</h3>
        </div>
        <div class="card-body">
            @include('fruitstory::orders.form')
        </div>
    </div>
@endsection

app/Modules/Fruitstory/Resources/views/orders/form.blade.php
@if($model->exists)
    {{ Form::open(array('url' => secure_url_env(route('lora.orders.update', $model->id)),'method'=> 'PUT', 'name'=>'updateCategory', 'files' => true,
     'class' => 'form-horizontal'))}}
@else
    {{ Form::open(array('url' => secure_url_env(route('lora.orders.store')),'method'=> 'POST', 'name'=>'postCategory', 'files' => true, 'class' => 'form-horizontal'))}}
@endif


@if (count($errors) > 0)
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif

<div class="form-group{{ $errors->has('title') ? ' has-error' : '' }}">
    <label for="title" class="col-md-2 control-label">Пользователь</label>

    <div class="col-md-9">
        {{Form::select('user_id', $model->listPersons, $model->user_id, ['class' => 'form-control', 'id' => 'category-name',
        'placeholder' => 'choose']) }}

        @if ($errors->has('user_id'))
            <span class="help-block">
                <strong>{{ $errors->first('user_id') }}</strong>
            </span>
        @endif
    </div>
</div>

<div class="form-group{{ $errors->has('title') ? ' has-error' : '' }}">
    <label for="title" class="col-md-2 control-label">Способ оплаты</label>

    <div class="col-md-9">
        {{Form::select('type_payment', $model->typePayments, $model->type_payment, ['class' => 'form-control', 'id' => 'category-name',
        'placeholder' => 'choose']) }}

        @if ($errors->has('payment_type'))
            <span class="help-block">
                <strong>{{ $errors->first('payment_type') }}</strong>
            </span>
        @endif
    </div>
</div>

<div class="form-group">
    <label class="col-md-2 control-label" for="title">Статус</label>
    <div class="col-md-9">
    {{Form::select('status_id', $model->statuses, $model->status_id,['class'   => 'form-control'])}}
    </div>
</div>

<div class="form-group">
    <div class="col-md-12">
        <button type="submit" class="btn btn-primary">
            @if($model->exists)Обновить@else Создать @endif
        </button>
    </div>
</div>
{{Form::close()}}

app/Modules/Fruitstory/Resources/views/orders/index.blade.php
@extends('lora::layouts.app')

@section('content')
    <div class="card card-default">
        <div class="card-header">
            <h3>Список заказов</h3>
        </div>

        <div class="card-body">
            <table class="table table-hover" data-form="deleteForm">
                <thead>
                <tr>
                    <th>id</th>
                    <th>Клиент</th>
                    <th>Товары</th>
                    <th>Сумма</th>
                    <th>Доставка</th>
                    <th>Комментарии</th>
                    <th>Оплачено</th>
                    <th>Статус</th>
                    <th>Действия</th>
                </tr>
                </thead>
                <tbody>

                @foreach($models as $model)
                    <tr>
                        <td>{{$model->id}}</td>
                        <td>
                            <p>{{$model->user->fullName ?? 'Не указано'}}</p>
                            <p>{{$model->user->phone ?? 'Не указано'}}</p>
                            <p>{{$model->createdDate ?? 'Не указано'}}</p>
                            <p>Cпособ оплаты: {{$model->payment}}</p>
                        </td>
                        <td>
                            <p>Заказано товаров: {{$model->orderItems->count()}}</p>
                            <a href="{{route('lora.orders.items.index', $model->id)}}">Смотреть</a>
                        </td>
                        <td><span>{{$model->total}} тг.</span></td>
                        <td>
                            <p>Тип: {{$model->delivery ?? 'Не указано'}}</p>
                            <p>Адрес: {{$model->delivery_address ?? 'Не указано'}}</p>
                            <p>Дата: {{$model->delivery_date ?? 'Не указано'}}</p>
                            <p>Цена: {{$model->area->cost ?? 'Не указано'}}</p>
                        </td>
                        <td>{{$model->comment ?? 'Не указано'}}</td>
                        <td>{{$model->is_paid ? 'ДА' : 'НЕТ'}}</td>
                        <td>{{$model->status}}</td>
                        <td>
                            <a class="btn btn-sm btn-primary" href="{{route('lora.orders.edit', $model->id)}}">
                                <i class="fas fa-edit" aria-hidden="true"></i></a>

                            <button class="btn btn-sm btn-danger delete" type="button"
                                    data-target="#confirm"
                                    data-toggle="modal" data-action="{{route('lora.orders.destroy', $model->id)}}">
                                <i class="fas fa-times" aria-hidden="true"></i></button>
                        </td>
                    </tr>

                @endforeach
                </tbody>
            </table>
        </div>
    </div>
    <div class="col-md-10">
        <div class="form-group">
            {{ $models->links() }}
        </div>
    </div>
    @include('lora::modals.base_modal')
@endsection

@section('js-append')

    <script>
        $('#confirm').on('show.bs.modal', function (event) {
            var button = $(event.relatedTarget);
            var modal = $(this);

            modal.find('#removeForm').attr('action', button.data('action'))
        })
    </script>
@endsection