app/Modules/Fruitstory/routes/web.php
<?php

Route::group([
    'prefix' => 'lora',
    'as' => 'lora.',
    'middleware' => [ 'web', 'language'],
    'namespace' => 'App\Modules\Fruitstory\Http\Controllers'], function () {

    Route::group(['middleware' => 'guardAuth:admin'], function() {
        Route::resource('orders.items', 'OrderItemsController');
        Route::resource('orders', 'OrdersController');
        Route::resource('categories','CategoryController');
        Route::post('products/{product}','ProductController@update')->name('products.update');
        Route::resource('products','ProductController')->except('update');
        Route::resource('users','UserResourceController');
        Route::resource('units', 'UnitsController');
        Route::delete('news/{news_id}/images/{image_id}','NewsController@removeImage');
        Route::resource('news', 'NewsController');
        Route::resource('promo', 'PromoCodeController');
        Route::resource('delivery-areas', 'DeliveryAreasController');
        Route::resource('cities', 'CitiesController');
        Route::get('bonuses', 'BonusesController@index');
        Route::put('bonuses', 'BonusesController@update')->name('bonuses.update');

    });
});

app/Modules/Fruitstory/Http/Controllers/ProductController.php
<?php

namespace App\Modules\Fruitstory\Http\Controllers;

use App\Http\Requests\Request;
use App\Http\Requests\StoreProductRequest;
use Dosarkz\Lora\Installation\Modules\Lora\Models\Image;
use App\Models\Product;
use App\Models\Tag;
use Dosarkz\LaravelUploader\ImageUploader;
use Dosarkz\Lora\Installation\Modules\Lora\Http\Controllers\BasicController;

class ProductController extends BasicController
{
    public function __construct()
    {
        $this->setModel(new Product());
        $this->setViewPath('fruitstory');
    }

    public function index()
    {
        $models = $this->getModel()->filter()->orderBy('id', 'DESC')->paginate(15);
        $categories = $this->getModel()->ListCategories;
        return $this->view('products.index', compact('models','categories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $model = $this->getModel();
        return $this->view('products.create', compact('model'));
    }

    /**
     * @param StoreProductRequest $request
     * @return \Illuminate\Http\RedirectResponse
     *
     */
    public function store(StoreProductRequest $request)
    {
        $data = $request->all();

        $data['alias'] = self::trans_url($request->input('title'));
        $data['user_id'] = auth('admin')->user()->id;

      $model =  $this->getModel()->create($data);

        if ($request->has('tags')) {
            $list = explode(',', $request->input('tags'));

            foreach ($list as $item) {
                Tag::create([
                    'title' => $item,
                    'product_id' => $model->id
                ]);
            }
        }

        if ($request->hasFile('image_id')) {
            $uploader = new ImageUploader($request->file('image_id'), 'images/products/');

            $model->image()->create([
                'name' => $uploader->getFileName(),
                'thumb' => $uploader->getThumb(),
                'path' => $uploader->destination
            ]);
        }

        return redirect(route('lora.products.index'))->with('success', 'success');
    }


    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $model = $this->getModel()->findOrFail($id);
        return $this->view('products.edit', compact('model'));
    }

    /**
     * @param StoreProductRequest $request
     * @param $id
     * @return \Illuminate\Foundation\Application|\Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function update(StoreProductRequest $request, $id)
    {
        $model = $this->getModel()->find($id);
        $data = $request->all();

        if ($request->has('tags')) {
            $list = explode(',', $request->input('tags'));

            $model->tags()->delete();

            foreach ($list as $item) {
                Tag::firstOrCreate([
                    'title' => $item,
                    'product_id' => $model->id
                ]);
            }
        }

        if ($request->hasFile('image_id')) {
            $model->images()->delete();
            $uploader = new ImageUploader($request->file('image_id'), 'images/products/');

            $model->image()->create([
                'name' => $uploader->getFileName(),
                'thumb' => $uploader->getThumb(),
                'path' => $uploader->destination
            ]);
        }
        $model->update($data);
        return redirect(route('lora.products.index'))->with('success', 'success');
    }

    /**
     * @param $id
     * @return \Illuminate\Foundation\Application|\Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function destroy($id)
    {
        $model = $this->getModel()->find($id);
        $model->delete();

        return redirect(route('lora.products.index'))->with('success', 'deleted');
    }

}

app/Modules/Fruitstory/Resources/views/products/create.blade.php
@extends('lora::layouts.app')

@section('content')

    <div class="card">
        <div class="card-header">
            <h3 class="panel-heading">Создать новую продукцию</h3>
        </div>
        <div class="card-body">
            @include('fruitstory::products.form')
        </div>
    </div>

@endsection


@section('js-append')
    <script src="/js/taginput/bootstrap-tagsinput.min.js"></script>

    <script>
        $('#tags-input').on('itemAdded', function(event) {
            $("#tags").attr('value', $("#tags-input").val());
        });

        $('#tags-input').on('itemRemoved', function(event) {
            $("#tags").attr('value', $("#tags-input").val());
        });

    </script>
@endsection

@section('css')
    <link rel="stylesheet" href="/js/taginput/bootstrap-tagsinput.css">
@endsection

app/Modules/Fruitstory/Resources/views/products/edit.blade.php
@extends('lora::layouts.app')

@section('content')

    <div class="card">
        <div class="card-header">
            <h3 class="panel-heading">Редактировать продукт # {{$model->id}}</h3>
        </div>
        <div class="card-body">
            @include('fruitstory::products.form')
        </div>
    </div>

@endsection

@section('js-append')
    <script src="/js/taginput/bootstrap-tagsinput.min.js"></script>

    <script>
        $('#tags-input').on('itemAdded', function(event) {

            $("#tags").attr('value', $("#tags-input").val());
        });

        $('#tags-input').on('itemRemoved', function(event) {
            $("#tags").attr('value', $("#tags-input").val());
        });
    </script>
@endsection

@section('css')
    <link rel="stylesheet" href="/js/taginput/bootstrap-tagsinput.css">
@endsection

app/Modules/Fruitstory/Resources/views/products/form.blade.php
@if($model->exists)
    {{ Form::open(array('url' => secure_url_env(route('lora.products.update', $model->id)),'method'=> 'POST', 'name'=>'updateCategory', 'files' => true,
     'class' => 'form-horizontal', 'onkeypress'   =>  'return event.keyCode != 13;'))}}
@else
    {{ Form::open(array('url' => secure_url_env(route('lora.products.store')),'method'=> 'POST', 'name'=>'postCategory',
    'files' => true, 'class' => 'form-horizontal', 'onkeypress'   =>  'return event.keyCode != 13;'))}}
@endif


@if (count($errors) > 0)
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif

<div class="form-group{{ $errors->has('title') ? ' has-error' : '' }}">
    <label for="title" class="col-md-2 control-label">Название</label>

    <div class="col-md-9">

        {{Form::text('title', $model->title, ['class' => 'form-control', 'id' => 'category-name']) }}

        @if ($errors->has('title'))
            <span class="help-block">
                <strong>{{ $errors->first('title') }}</strong>
            </span>
        @endif
    </div>
</div>

<div class="form-group{{ $errors->has('description') ? ' has-error' : '' }}">
    <label for="title" class="col-md-2 control-label">Описание</label>

    <div class="col-md-9">

        {{Form::textarea('description', $model->description, ['class' => 'form-control', 'id' => 'product-description']) }}

        @if ($errors->has('description'))
            <span class="help-block">
                <strong>{{ $errors->first('description') }}</strong>
            </span>
        @endif
    </div>
</div>

<div class="form-group{{ $errors->has('image_id') ? ' has-error' : '' }}">
    <label for="title" class="col-md-2 control-label">Фото</label>

    <div class="col-md-9">

        {{Form::file('image_id', ['class' => 'form-control', 'id' => 'product-image_id']) }}

        @if ($errors->has('image_id'))
            <span class="help-block">
                <strong>{{ $errors->first('image_id') }}</strong>
            </span>
        @endif
        @if($model->image)
            <div class="form-group mt-5">
                <img class="img-thumbnail " src="/{{$model->image->getThumb()}}" width="150" height="150" alt="">
            </div>
        @endif
    </div>
</div>

<div class="form-group{{ $errors->has('unit_id') ? ' has-error' : '' }}">
    <label for="title" class="col-md-2 control-label">Ед. измерения</label>

    <div class="col-md-9">

        {{Form::select('unit_id', $model->unitList, $model->unit_id, ['class' => 'form-control', 'id' => 'product-unit',
        'placeholder'   =>  'Выберите ед']) }}

        @if ($errors->has('unit_id'))
            <span class="help-block">
                <strong>{{ $errors->first('unit_id') }}</strong>
            </span>
        @endif
    </div>
</div>

<div class="form-group{{ $errors->has('unit_starting_point') ? ' has-error' : '' }}">
    <label for="title" class="col-md-2 control-label">Начальное значение</label>

    <div class="col-md-9">

        {{Form::text('unit_starting_point', $model->unit_starting_point, ['class' => 'form-control', 'id' => 'category-name']) }}

        @if ($errors->has('unit_starting_point'))
            <span class="help-block">
                <strong>{{ $errors->first('unit_starting_point') }}</strong>
            </span>
        @endif
    </div>
</div>

<div class="form-group{{ $errors->has('unit_step') ? ' has-error' : '' }}">
    <label for="title" class="col-md-2 control-label">Шаг</label>

    <div class="col-md-9">

        {{Form::text('unit_step', $model->unit_step, ['class' => 'form-control', 'id' => 'category-name']) }}

        @if ($errors->has('unit_step'))
            <span class="help-block">
                <strong>{{ $errors->first('unit_step') }}</strong>
            </span>
        @endif
    </div>
</div>


<div class="form-group{{ $errors->has('cost') ? ' has-error' : '' }}">
    <label for="title" class="col-md-2 control-label">Цена</label>

    <div class="col-md-9">

        {{Form::number('cost',$model->cost, ['class' => 'form-control', 'id' => 'product-cost']) }}

        @if ($errors->has('cost'))
            <span class="help-block">
                <strong>{{ $errors->first('cost') }}</strong>
            </span>
        @endif
    </div>
</div>

<div class="form-group{{ $errors->has('category_id') ? ' has-error' : '' }}">
    <label for="title" class="col-md-2 control-label">Категория</label>

    <div class="col-md-9">

        {{Form::select('category_id', $model->listCategories,$model->category_id, ['class' => 'form-control', 'id' => 'product-category_id',
        'placeholder' => 'Не выбрана']) }}

        @if ($errors->has('category_id'))
            <span class="help-block">
                <strong>{{ $errors->first('category_id') }}</strong>
            </span>
        @endif
    </div>
</div>


<div class="form-group{{ $errors->has('position') ? ' has-error' : '' }}">
    <label for="position" class="col-md-2 control-label">Позиция</label>

    <div class="col-md-9">

        {{Form::number('position', $model->exists ? $model->position : \App\Models\Category::maxPosition(),
        ['class' => 'form-control']) }}

        @if ($errors->has('position'))
            <span class="help-block">
                                        <strong>{{ $errors->first('position') }}</strong>
                                    </span>
        @endif
    </div>
</div>

<div class="form-group">
    <label class="col-md-2 control-label" for="title">Статус</label>
    <div class="col-md-9">
    {{Form::select('status_id', [1=> 'Активен', 0 => 'Не активен'], $model->status_id,['class'   => 'form-control', 'placeholder' =>
    'Не выбран'])}}
    </div>
</div>
<div class="form-group">
    <label class="col-md-2 control-label" for="title">Тэги</label>
    <div class="col-md-9">
        {{Form::text('tags', $model->taglist,['data-role'    =>  'tagsinput', 'id'   =>  'tags-input' ])}}
        {{Form::hidden('tags',null, ['id'  =>  'tags'])}}
    </div>
</div>

<div class="form-group">
    <div class="col-md-12">
        <button type="submit" class="btn btn-primary">
            @if($model->exists)Обновить@else Создать @endif
        </button>
    </div>
</div>
{{Form::close()}}

app/Modules/Fruitstory/Resources/views/products/index.blade.php
@extends('lora::layouts.app')

@section('content')
        <div class="card card-blue">
            <div class="card-body">

                <div class="panel panel-default">
                    <div class="panel-body">
                        <form class="form" role="form" method="get">
                            <div class="row">
                                <div class="form-group col-md-3">
                                    <label class="control-label" for="q">Поиск по названию</label>
                                    <input type="text" name="q" class="form-control input-sm" id="q" value="{{request('q')}}">
                                </div>

                                <div class="form-group col-md-3">
                                    <label class="control-label" for="category_id">Категория</label>

                                    {{Form::select('category_id', $categories, request()->input('category_id'),
['class' => 'form-control product-category_id', 'id' => 'product-category_id','placeholder' => 'Не выбрана']) }}

                                </div>

{{--                                <div class="form-group col-md-3">--}}
{{--                                    <label class="control-label" for="id">ID</label>--}}
{{--                                    <input type="text" name="id" class="form-control input-sm" id="id" value="{{request('id')}}">--}}
{{--                                </div>--}}
                            </div>

                            <div class="form-group">
                                <button type="submit" class="btn btn-warning filter-col">
                                    <span class="glyphicon glyphicon-record"></span> Найти
                                </button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>

    <div class="card card-default">
        <div class="card-header">
            <h3>Список Продукции</h3>
        </div>

        <div class="card-body">
            <table class="table table-hover" data-form="deleteForm">
                <thead>
                <tr>
                    <th>id</th>
                    <th>Название</th>
                    <th>Категория</th>
                    <th>Статус</th>
                    <th>Позиция</th>
                    <th>Действия</th>
                </tr>
                </thead>
                <tbody>
                @foreach($models as $item)
                    <tr>
                        <td>{{$item->id}}</td>
                        <td>{{$item->title}}</td>
                        <td>{{$item->category ? $item->category->title : null}}</td>
                        <td>{{$item->status_id == 1 ? 'Активный' : 'Не активен'}}</td>
                        <td>{{$item->position}}</td>
                        <td>
                            <a class="btn btn-sm btn-primary" href="{{route('lora.products.edit', $item->id)}}">
                                <i class="fas fa-edit" aria-hidden="true"></i></a>

                            <button class="btn btn-sm btn-danger delete" type="button"
                                    data-target="#confirm"
                                    data-toggle="modal" data-action="{{route('lora.products.destroy', $item->id)}}">
                                <i class="fas fa-times" aria-hidden="true"></i></button>
                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>
        </div>
        <div class="card-footer">
            <div class="col-md-10">
                <div class="form-group">
                    {{ $models->appends(request()->except('page'))->links() }}
                </div>
            </div>
            @include('lora::modals.base_modal')
        </div>
    </div>
@endsection
@section('js-append')
    <script src="/vendor/admin/adminlte/plugins/select2/js/select2.js"></script>
    <script>
        $('#confirm').on('show.bs.modal', function (event) {
            var button = $(event.relatedTarget);
            var modal = $(this);

            modal.find('#removeForm').attr('action', button.data('action'))
        })
        $(document).ready(function() {
            $('.product-category_id').select2();
        });

    </script>
@endsection

@section('css')
    <link rel="stylesheet" href="/vendor/admin/adminlte/plugins/select2/css/select2.css">
    <link rel="stylesheet" href="/vendor/admin/adminlte/plugins/select2-bootstrap4-theme/select2-bootstrap4.css">
@endsection