app/Modules/Fruitstory/routes/web.php
<?php

Route::group([
    'prefix' => 'lora',
    'as' => 'lora.',
    'middleware' => [ 'web', 'language'],
    'namespace' => 'App\Modules\Fruitstory\Http\Controllers'], function () {

    Route::group(['middleware' => 'guardAuth:admin'], function() {
        Route::resource('orders.items', 'OrderItemsController');
        Route::resource('orders', 'OrdersController');
        Route::resource('categories','CategoryController');
        Route::post('products/{product}','ProductController@update')->name('products.update');
        Route::resource('products','ProductController')->except('update');
        Route::resource('users','UserResourceController');
        Route::resource('units', 'UnitsController');
        Route::delete('news/{news_id}/images/{image_id}','NewsController@removeImage');
        Route::resource('news', 'NewsController');
        Route::resource('promo', 'PromoCodeController');
        Route::resource('delivery-areas', 'DeliveryAreasController');
        Route::resource('cities', 'CitiesController');
        Route::get('bonuses', 'BonusesController@index');
        Route::put('bonuses', 'BonusesController@update')->name('bonuses.update');

    });
});

app/Modules/Fruitstory/Resources/views/promo/create.blade.php
@extends('lora::layouts.app')

@section('content')
    <div class="card">
        <div class="card-header">
            <h3 class="panel-heading">Создать новый код</h3>
        </div>
        <div class="card-body">
            @include('fruitstory::promo.form')
        </div>
    </div>
@endsection

app/Modules/Fruitstory/Resources/views/promo/edit.blade.php
@extends('lora::layouts.app')

@section('content')
    <div class="card">
        <div class="card-header">
            <h3 class="panel-heading">Редактировать код # {{$model->id}}</h3>
        </div>
        <div class="card-body">
            @include('fruitstory::promo.form')
        </div>
    </div>
@endsection

app/Modules/Fruitstory/Resources/views/promo/form.blade.php
@if($model->exists)
    {{ Form::open(array('url' => secure_url_env(route('lora.promo.update', $model->id)),'method'=> 'PUT', 'name'=>'updateCategory', 'files' => true,
     'class' => 'form-horizontal'))}}
@else
    {{ Form::open(array('url' => secure_url_env(route('lora.promo.store')),'method'=> 'POST', 'name'=>'postCategory', 'files' => true, 'class' => 'form-horizontal'))}}
@endif


@if (count($errors) > 0)
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif


<div class="form-group{{ $errors->has('title') ? ' has-error' : '' }}">
    <label for="title" class="col-md-2 control-label">Код</label>

    <div class="col-md-9">

        {{Form::text('title', $model->title,
        ['class' => 'form-control']) }}

        @if ($errors->has('title'))
            <span class="help-block">
            <strong>{{ $errors->first('title') }}</strong>
        </span>
        @endif
    </div>
</div>



<div class="form-group{{ $errors->has('cost') ? ' has-error' : '' }}">
    <label for="position" class="col-md-2 control-label">Сумма скидки</label>

    <div class="col-md-9">

        {{Form::number('cost', $model->cost,
        ['class' => 'form-control']) }}

        @if ($errors->has('cost'))
            <span class="help-block">
            <strong>{{ $errors->first('cost') }}</strong>
        </span>
        @endif
    </div>
</div>

<div class="form-group{{ $errors->has('expired_at') ? ' has-error' : '' }}">
    <label for="position" class="col-md-2 control-label">Срок действия промокода</label>

    <div class="col-md-9">

        {{Form::date('expired_at', date('Y-m-d',strtotime($model->expired_at)),
        ['class' => 'form-control']) }}

        @if ($errors->has('expired_at'))
            <span class="help-block">
                <strong>{{ $errors->first('expired_at') }}</strong>
            </span>
        @endif
    </div>
</div>


<div class="form-group{{ $errors->has('min_amount') ? ' has-error' : '' }}">
    <label for="min_amount" class="col-md-2 control-label">Сумма заказа ( больше или равно)</label>

    <div class="col-md-9">

        {{Form::number('min_amount', $model->min_amount,
        ['class' => 'form-control']) }}

        @if ($errors->has('min_amount'))
            <span class="help-block">
            <strong>{{ $errors->first('min_amount') }}</strong>
        </span>
        @endif
    </div>
</div>

<div class="form-group{{ $errors->has('user_id') ? ' has-error' : '' }}">
    <label for="min_amount" class="col-md-4 control-label">Партнер</label>

    <div class="col-md-9">

        {{Form::select('user_id', $users,$model->user_id,['class'   => 'form-control', 'placeholder' => 'Не выбрано'])}}

        @if ($errors->has('user_id'))
            <span class="help-block">
            <strong>{{ $errors->first('user_id') }}</strong>
        </span>
        @endif
    </div>
</div>


<div class="form-group{{ $errors->has('percentage_of_user') ? ' has-error' : '' }}">
    <label for="min_amount" class="col-md-4 control-label">Бонус для партнера</label>

    <div class="col-md-9">
        {{Form::number('percentage_of_user', $model->percentage_of_user, ['class' => 'form-control']) }}

        @if ($errors->has('percentage_of_user'))
            <span class="help-block">
            <strong>{{ $errors->first('percentage_of_user') }}</strong>
        </span>
        @endif
    </div>
</div>

<div class="form-group">
    <div class="col-md-12">
        <button type="submit" class="btn btn-primary">
            @if($model->exists)Обновить@else Создать @endif
        </button>
    </div>
</div>
{{Form::close()}}

app/Modules/Fruitstory/Resources/views/promo/index.blade.php
@extends('lora::layouts.app')

@section('content')

    <div class="card card-default">
        <div class="card-header">
            <h3>Список Кодов</h3>
        </div>

        <div class="card-body">
            <table class="table table-hover" data-form="deleteForm">
                <thead>
                <tr>
                    <th>id</th>
                    <th>Код</th>
                    <th>Сумма от</th>
                    <th>Дата завершения</th>
                    <th>Использовано</th>
                    <th>Действия</th>
                </tr>
                </thead>
                <tbody>
                @foreach($models as $model)
                    <tr>
                        <td>{{$model->id}}</td>
                        <td>{{$model->title}}</td>
                        <td>{{$model->cost}}</td>
                        <td>{{$model->expired_at->format('Y-m-d')}}</td>
                        <td>{{$model->used}}</td>
                        <td>
                            <a class="btn btn-sm btn-primary" href="{{route('lora.promo.edit', $model->id)}}">
                                <i class="fas fa-edit" aria-hidden="true"></i></a>

                            <button class="btn btn-sm btn-danger delete" type="button"
                                    data-target="#confirm"
                                    data-toggle="modal" data-action="{{route('lora.promo.destroy', $model->id)}}">
                                <i class="fas fa-times" aria-hidden="true"></i></button>
                        </td>
                    </tr>

                @endforeach
                </tbody>
            </table>
        </div>
        <div class="card-footer">
            <div class="col-md-10">
                <div class="form-group">
                    {{ $models->links() }}
                </div>
            </div>
            @include('lora::modals.base_modal')
        </div>
    </div>
@endsection

@section('js-append')

    <script>
        $('#confirm').on('show.bs.modal', function (event) {
            var button = $(event.relatedTarget);
            var modal = $(this);

            modal.find('#removeForm').attr('action', button.data('action'))
        })
    </script>
@endsection